screwdriver-cd/executor-k8s

index.js
test/index.test.js

Enable `.start()` endpoint to be usable and useless

Minimalistic start endpoint

---

config/job.yaml.tim

Updated resource limits, closes #3 when merged
- removed resource limits from launcher
- multiplied resource limits by 4
http://kubernetes.io/docs/user-guide/production-pods/#resource-management

Add initial resource limits

---

index.js
package.json
test/index.test.js

Add stream function to stream logs. This makes a call to get the pod's information based on sdbuild labelSelector. From there, we get the podname and stream the logs of that pod.
This will be used by the plugin-builds https://github.com/screwdriver-cd/plugin-builds/pull/22

Add function to stream logs

---

config/job.yaml.tim

Reverts screwdriver-cd/executor-k8s#4
The limits we implemented are too high for the current infrastructure. This is to remove the limits until we can determine better settings for the configuration

Revert "Add initial resource limits"

---

index.js
test/index.test.js

This PR wraps the request.get function in a Readable stream that is passed back to the reply object
Currently, the implementation relies on a `.on('response')` event being called which only occurs once the entire log is loaded, and not for the stream

Stream the Logs

---

index.js
package.json
test/index.test.js

This PR is integrating the circuit-breaker module from https://github.com/screwdriver-cd/circuit-fuses/pull/1
The PR is creating a fuse around calls to the Kubernetes cluster
I don't think it's possible to wrap the actual streaming of logs in a fuse because we need to be returning a readable stream of the Request.get object

Add in circuit breakers

---

README.md
index.js
package.json
test/index.test.js

Resolves #20 
Resolves #17 
This PR changes the configuration of the token and host to be done via the constructor of the object
It also adds in the new screwdriver-executor-base (https://github.com/screwdriver-cd/executor-base) class that enables input validation of executor functions
Also added in a README

Configure via Constructor; Use new Base class

---

index.js
test/index.test.js

This PR adds in an executor stop function for the executor-k8s
It calls delete on the jobUri endpoint including a labelSelector for the `sdbuild` that is set in the _start function

Executor Stops

---

README.md
config/job.yaml.tim
index.js
package.json
test/index.test.js

[Feature](https://github.com/screwdriver-cd/screwdriver/issues/77)
Passing:
- buildId - Build Identifier (to look up stuff)
- container - Container to start in
- apiUri - URI to hit our API
- token - Token to be able to read/write from the API
Blocked on https://github.com/screwdriver-cd/executor-base/pull/13
@jer I need the expected version of the JobTools that will contain this new launcher

[F1] Executing Launcher with new arguments (3rd)

---

index.js
test/index.test.js

This PR adds in a getter for the executor that retrieves stats of the circuit breaker being used.
The functions called on the breaker are exposed via the circuit-fuses class https://github.com/screwdriver-cd/circuit-fuses
I'm not sure if we want to standardize in the `executor-base` to have a stats method, but this is a start

Add getter for breaker stats

---

config/job.yaml.tim

This uses the new 1.3 _alpha_ init container feature as described in http://kubernetes.io/docs/user-guide/production-pods/#handling-initialization
It also allows us to use tini as pid 1 :)
Should be merged AFTER https://github.com/screwdriver-cd/job-tools/pull/20

Using init containers AND the power of tini

---

README.md
config/job.yaml.tim
index.js
test/index.test.js

- No longer using logVersion
- No longer creating log container
- Using api and store from ecosystem
- Scoping Kubernetes config in constructor
Not bumping major because not included in SD yet. https://github.com/screwdriver-cd/screwdriver/pull/270

Simplifying the Kubernetes config and using the new store API

---

index.js
test/index.test.js

When you are running in a namespace other than `default` you have to
specify `sevice.namespace` for kubedns to resolve, rather than just
`service`. If you are in the default namespace, `service.namespace`
still works correctly. `kubernetes` runs in the `default` namespace.

Fixed the default kubernetes hostname

---

CHANGELOG.md
config/job.yaml.tim
package.json
test/index.test.js

We have some legacy containers with contents in `/opt/screwdriver`.  This changes the mounted location to `/opt/sd` to prevent any namespace collisions.

fix: Switching to /opt/sd to prevent collisions

---

config/job.yaml.tim

- We now have buildId as number which failed the job template for kubernetes
- Add double quote to make it a string

fix: add double quote for buildId(number)

---

README.md
index.js
test/index.test.js

`executor-router` will require all `executor plugins` no matter what default you pick. So when I test it locally using docker as my default, it complains that `/var/run/secrets/kubernetes.io/serviceaccount/token` does not exist which is annoying and does not make any sense.
This PR will check if the path exist, if not, set the token to `empty`.
Related to https://github.com/screwdriver-cd/screwdriver/issues/604

fix(604): set token to empty if no token in config and tokenPath not exists

---

config/pod.yaml.tim
index.js
package.json
test/index.test.js

We mainly use `k8s-executor` plugin in our cluster, and some builds fail due to lack of resources.
So, This PR add `HIGH` resource for cpu and ram to `k8s` executor just like [k8s-vm](https://github.com/screwdriver-cd/executor-k8s-vm/pull/10).
[758](https://github.com/screwdriver-cd/screwdriver/issues/758), [759](https://github.com/screwdriver-cd/screwdriver/issues/759)

feat: Add HIGH resource for cpu and ram

---

screwdriver.yaml

Newer version of `semantic-release` package requires node>=8,
so I fixed to use `semantic-release` template like [this](https://github.com/screwdriver-cd/executor-k8s-vm/pull/9).
https://cd.screwdriver.cd/pipelines/28/builds/13391

fix: use semantic-release template for publish

---

config/pod.yaml.tim

Screwdriver.cd is now using Init Containers with alpha annotations, but alpha annotations are not supported in Kubernetes 1.8 or greater.
Use new syntax of Init Containers.
Please refer to https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
- This new syntax doesn't work in Kubernetes 1.5
- same as https://github.com/screwdriver-cd/executor-k8s-vm/pull/16

fix: update syntax of Init Containers 

---

index.js
test/index.test.js

Currently, it defaults to require 2 cpu to start the pod. Our nodes have only 2 cpu so a lot of builds get stuck. This PR makes it configurable by the cluster, so we can modify this value to something smaller.

fix: making high/low cpu/memory configurable by cluster

---

config/pod.yaml.tim

Add store url argument when call launch command.
We need to use store url when use sd-cmd. 
By this [PR](https://github.com/screwdriver-cd/launcher/pull/138), we can set store api. 
Call launch command with `--store-uri` argument.
[launcher PR for store url argument](https://github.com/screwdriver-cd/launcher/pull/138)

feat: set store uri when launch

---

config/pod.yaml.tim

Mounts the Habitat directory in a different volume.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/877

feat(habitat): Adding support for mounting Habitat directory

---

config/pod.yaml.tim

Some users want to use public docker images with floating tags that we don't recommend to use on Screwdriver.cd including "node:8" and "python:3.4".
But they are very convenient to use for users who want to keep their build environment the latest.
For example, given the job that uses "node:8".
Each build may use different images every time the case some nodes have "node:8" in their cache and others don't. It makes users confusing.
I added new settings `imagePullPolicy` and set it to `Always`.  Every builds on Kubernetes executor will confirm for the update by this change.
This resolves screwdriver-cd/screwdriver#869.

Fix imagePullPolicy setting to "Always"

---

config/pod.yaml.tim
index.js
test/index.test.js

Build timeouts have a default value of 5400 seconds. We want to allow users to override the value. Eventually we will put in efforts to enforce boundaries on these values.
Use an annotation for users to configure their own timeouts. Default is 5400 seconds.
* Feature issue
* https://github.com/screwdriver-cd/screwdriver/issues/545
* Hyperctl parameter for build timeout
* https://github.com/screwdriver-cd/hyperctl-image/pull/19

feat: annotation for customizing build timeouts

---

config/pod.yaml.tim

The `build-timeout` flag is being passed in _after_ the Build ID argument. This means that even though we're specifying the value, the launcher won't respect it
Place all the flags before the passed-in arguments

fix: build-timeout flag comes before build ID arg

---

index.js
test/index.test.js

The default  `nodeSelectors` and `preferredNodeSelectors` are `{}`. It creates empty affinity configs so it causes this error.
```
Failed to create pod: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"3\" is invalid: spec.affinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms: Required value: must have at least one node selector term","reason":"Invalid","details":{"name":"3","kind":"Pod","causes":[{"reason":"FieldValueRequired","message":"Required value: must have at least one node selector term","field":"spec.affinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms"}]},"code":422}
```
This PR fixes this problem.
Related: https://github.com/screwdriver-cd/screwdriver/issues/972

fix(972): fix when a selector is empty object

---

index.js
test/index.test.js

Allow cluster admin to configure default build timeout for the cluster
Related: screwdriver-cd/screwdriver#545

fix(545): support cluster timeout

---

index.js
package.json
test/index.test.js

Resolving to `null` since it's not supported. 
We need this because models always call `_startPeriodic` for `update`
Blocked by: https://github.com/screwdriver-cd/executor-base/pull/39
Related: https://github.com/screwdriver-cd/screwdriver/issues/688

[2] fix: add start/stop periodic functions

---

config/pod.yaml.tim

This prevents the build containers from getting access to a credential
that can be used to access the K8s API.  See [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server) for more information.

feat: Prevent K8s pods from getting API credentials

---

index.js
package.json
test/index.test.js

- When build starts in executor, call [`exchangeTokenForBuild()`](https://github.com/screwdriver-cd/executor-base/pull/42) method which is added in `executor-base` to get build JWT, and replace `config.token` to the new JWT.
- `buildTimeout` argument can be passed to this method. It will be the expires time of build JWT.
- Issues: 
　https://github.com/screwdriver-cd/screwdriver/issues/998
　https://github.com/screwdriver-cd/screwdriver/issues/1030
　https://github.com/screwdriver-cd/screwdriver/issues/1075
- Related: (other PRs)
　https://github.com/screwdriver-cd/screwdriver/pull/1087
　https://github.com/screwdriver-cd/models/pull/245
　https://github.com/screwdriver-cd/executor-base/pull/42
　https://github.com/screwdriver-cd/executor-k8s/pull/84 …

fix(1030): [2] Add to call method in executor-base to get JWT for build

---

config/pod.yaml.tim

Requires:
* screwdriver-cd/launcher#179 and the new minimum launcher version.
* A major version bump
Use the Launcher's `launcher_entrypoint.sh` script as the new entrypoint command. 
* Dependent Launcher PR screwdriver-cd/launcher#179
* Related issue: screwdriver-cd/screwdriver#979

BREAKING CHANGE: Use launcher script as entrypoint command

---

config/pod.yaml.tim
package.json

Need to pass in API and Store urls.
Previously, we were passing in store uri like this:
```
--api-uri {{store_uri}}
```
Fixing the env var names in this PR. Also makes it more consistent with launcher.
```
--api-uri {{api_uri}} --store-uri {{store_uri}}
```
Related to https://github.com/screwdriver-cd/screwdriver/issues/1114

feat(1114): Pass in API URI to log-service. BREAKING CHANGE: switching var names [3]

---

config/pod.yaml.tim

To fetch build token in actual build execution, we fixed to exchange temporal token to build token in launcher process. 
However, also log-service uses token which is passed by `executor-*`.
To pass fetched build token to log-service and launcher, add the flag to launcher which only fetch token in launcher process, and use this flag to set fetched token before launcher and log-service processes start.
Detail: https://github.com/screwdriver-cd/screwdriver/issues/1167#issuecomment-409441739
Launcher passes wrapper script to run build. Therefore, each executor uses this script.
Use wrapper script to run build.
issue: https://github.com/screwdriver-cd/screwdriver/issues/1167
issue comment: https://github.com/screwdriver-cd/screwdriver/issues/1167#issuecomment-409441739
PR:
launcher: …

feat(1167): [5][small] Use wrapper script

---

.gitignore
index.js
test/index.test.js

Allow cluster admin to inject annotations to build pod yaml.
example annotations:
https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
Related to: https://github.com/screwdriver-cd/screwdriver/issues/818

fix(818): set k8s annotations if configured

---

config/pod.yaml.tim
index.js
package.json
test/index.test.js

- Add retry for starting pod and checking pod status
- Update status msg when pod is still pending after 5 retries
Basically the same as what we did for executor-k8s-vm: https://github.com/screwdriver-cd/executor-k8s-vm/blob/master/index.js

fix: add retry and update status msg when resources not available

---

index.js

Our current implementation of `setNodeSelector` appends multiple `nodeSelectorTerms` to the spec. This leads to an `OR` scheduling behavior where the pod can be scheduled on any node that is labled with any of the `nodeSelectors`. 
I believe we desire an `AND` scheduling behavior where the pod can be scheduled on any node that is labled with ALL of the `nodeSelectors`. This PR changes the implementation of `setNodeSelector` to honor this `AND` behavior of scheduling.
Update `setNodeSelector` to append multiple keys to a single `nodeSelectorTerm`
https://github.com/screwdriver-cd/screwdriver/issues/757
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
https://github.com/kubernetes/kubernetes/issues/44349 …

fix: Change setNodeSelector to use a single nodeSelectorTerm

---

index.js
test/index.test.js

A build didn't stop even if pushing stop button in the Completed step in a short time(roughly within 30 sec).
I modified to the build stops certainly after pushing stop button.
- Issues:
https://github.com/screwdriver-cd/screwdriver/issues/1261
- kubernetes-api Documents
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/

fix(1261): pod delete immediately when build has stopped.

---

index.js
test/index.test.js

Users can not get information why the build does not start on image pull error.
Shows the image pull error for users. Like below, like k8s-vm
This pr send the failure message to the queue-worker.
https://github.com/screwdriver-cd/queue-worker/pull/105
https://github.com/screwdriver-cd/executor-k8s/pull/98

fix: [1][small] Send image pull error to queue-worker

---

index.js
test/index.test.js

Update `build.stats.hostname` to indicate where the build is running on.
Will work on `image-pull time` separately after verifying this is working
Blocked by: https://github.com/screwdriver-cd/executor-base/pull/49
Related: https://github.com/screwdriver-cd/screwdriver/issues/1270

[5] feat(1270): update hostname for build

---

index.js
package.json
test/index.test.js

A couple issues to previous implementation:
- executor-k8s and executor-k8s-vm actually gets the params from redis. So `build` is not there
- We cannot store `build` in redis since its value might change, and `stop` needs exact params to delete from queue
Solution: blindly updates hostname here. The API will handle the logic to merge/update it. 
Related: 
https://github.com/screwdriver-cd/screwdriver/issues/1270
https://github.com/screwdriver-cd/screwdriver/pull/1423

fix: build is not in start params

---

index.js
test/index.test.js

We added `gracePeriodSeconds: 0` option to delete pod immediately.
Now, we don't have to use this option because SIGTERM processing is done correctly https://github.com/screwdriver-cd/launcher/pull/228#pullrequestreview-180903853. 
Therefore, I remove `gracePeriodSeconds: 0`option and use default settings.
https://github.com/screwdriver-cd/screwdriver/issues/1261
https://github.com/screwdriver-cd/screwdriver/issues/1403

fix(1403): Remove graceperiod settings

---

index.js
test/index.test.js

Previously we're checking the status `pending` and update the build stats (hostname, img pull start time) info after that. But that is not accurate since `pending` actually includes scheduling time and img pull time.
This PR will separate those 2 cases by making 2 different status calls, first to check `podScheduled` condition, second to check against the `pending` status. That way we can get an accurate time on when pod got scheduled and start img pulling 
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1270

fix: separate scheduling and img pulling status

---

index.js
test/index.test.js

Currently k8s executor abort a build if it uses nonexistent image. This process is done by checking if `state.waiting.reason` is "ErrImagePull" or not. But k8s change the reason after a while, to "ImagePullBackOff", so the build will remain for a long time.
* Add checks whether `reason` is "ImagePullBackOff" 
```
2014064-765x5                          0/1       ImagePullBackOff    0          2d
2014069-36855                          0/1       ErrImagePull        0          2d
```

Fix: Fix retry strategy for nonexistent image

---

.gitignore
config/pod.yaml.hbs
index.js
package.json
test/index.test.js

added annotations: 
`screwdriver.cd/dockerEnabled: true` (if not present or disabled, no additional docker in docker container will be created) 
`screwdriver.cd/dockerCpu: LOW` (same values as cpu) 
`screwdriver.cd/dockerRam: LOW` (same values as ram)
1. had to switch out tinytim for handlebars since tinytim on node doesn't support conditional templating. 
2. this will create a docker-in-docker container along side your build container which enable you to run in docker build / run from within the executor_k8s pod.

feat: Docker in docker as on option for executor k8s

---

index.js
package.json
test/index.test.js

[An error message](https://github.com/screwdriver-cd/executor-k8s/blob/2d52738caff561335b2aaa5c2620e4818b03c05b/index.js#L407-L409
) was not shown on UI and a build status was not changed even if users use invalid image.
This might be caused by pod's waiting reason is `PodInitializing` after [these retrying](https://github.com/screwdriver-cd/executor-k8s/blob/2d52738caff561335b2aaa5c2620e4818b03c05b/index.js#L391-L400).
To prevent this problem, `MAXATTEMPTS` and `RETRYDELAY` should be configurable.
https://github.com/screwdriver-cd/screwdriver/issues/1678

fix(1678): [2] add configurable retryDelay and maxAttempts

---

config/pod.yaml.hbs

Enable kata containers to run in privileged mode 

feat(818): Enable Privileged mode for kata containers

---

config/pod.yaml.hbs
index.js

By default, k8s pod runs in privileged mode.
By default, k8s pod runs in secured mode and privileged mode is enabled via a flag by admin.

feat(818): Security Context privileged mode configurable via a flag by admin

---

config/pod.yaml.hbs
index.js
test/index.test.js

* deprecate the use of "serviceAccount" for "serviceAccountName"
* make option for turning on automount of sa token
add config for serviceAccountName and automountServiceAccountToken
https://github.com/screwdriver-cd/screwdriver/issues/1955

feat: change service account config

---

config/pod.yaml.hbs

Top images to be cached in the node are not available as part of the node warm-up.
Send image metrics to Prometheus via pushgateway configuration. These metrics will be used to query top n images and cached in node as part of the node warm-up. 
[Launcher PR-335](https://github.com/screwdriver-cd/launcher/pull/335)

feat(818): push image name metrics to prometheus

---

index.js

Disk size customization not needed in contained + kata setup. By default, the container gets the max disk size based on the container storage setup. For docker runtime, it's possible via [docker-set-storage-options-per-container](https://docs.docker.com/engine/reference/commandline/run/#set-storage-driver-options-per-container)
This PR removes disk label config.

feat(818): remove disk label config

---

config/pod.yaml.hbs
index.js

Launcher container takes approx ~12secs due to hab install n copy. Support kata for Kubernetes version v1.12.0 or above.
Speed up launcher container setup time using symlink for hab. This is already available in executor-k8s-vm -> hyper route, porting it to executor-k8s. Add runtime class option to support kata for kubernetes higher version v1.12.0 or above [kata-containers-as-a-runtimeclass](https://github.com/kata-containers/documentation/blob/master/how-to/containerd-kata.md#kata-containers-as-a-runtimeclass).
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make …

feat(818): optimize initcontainer setup time, add runtimeclass for kata

---

config/pod.yaml.hbs

add metrics file in workspace dir to support missing metrics push to Prometheus
Add metrics file in workspace dir and update launcher start and end timestamp
[feat(818): Evaluate Kata Containers over HyperD](https://github.com/screwdriver-cd/screwdriver/issues/818)
[Launcher PR#342](https://github.com/screwdriver-cd/launcher/pull/342)

feat(818): add metrics file to support missing metrics push to prometheus

---

config/pod.yaml.hbs

Suffix buildid-with-prefix to the launcher container name, similar to build container name.
[feat(818): Evaluate Kata Containers over HyperD](https://github.com/screwdriver-cd/screwdriver/issues/818)

fix(818): add suffix build id to launcher container

---

config/pod.yaml.hbs
index.js

pipeline-id/job-id/build-id is available in both beta and prod environments, which results in incorrect metrics.
Add sd environment to metrics data.
[feat(818): Evaluate Kata Containers over HyperD](https://github.com/screwdriver-cd/screwdriver/issues/818)
[Launcher PR-352](https://github.com/screwdriver-cd/launcher/pull/352)

fix(818): add sd environment to env var

---

config/pod.yaml.hbs

Revert CPU config to support 0.5
https://github.com/screwdriver-cd/executor-k8s/pull/127

fix: revert cpu config to support 0.5 values

---

index.js
test/index.test.js

Custom memory value in annotation `screwdriver.cd/ram: 64` errors with invalid pod specification - ` Error: Failed to create pod: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod in version \"v1\" cannot be handled as a Pod: v1.Pod.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: Resources: v1.ResourceRequirements.Limits: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in #10 byte of ...|y\":\"NaNGi\"}},\"env\":[|..., bigger context ...|ources\":{\"limits\":{\"cpu\":\"16000m\",\"memory\":\"NaNGi\"}},"reason":"BadRequest","code":400} `
this.maxMemory is not configured and returning NaN for line# …

fix: custom memory value errors with invalid pod spec

---

config/pod.yaml.hbs
index.js
test/index.test.js

Build pods created with executor-k8s has `ClusterFirst` DNS policy set. This PR gives cluster admins flexibility to tweak build pods DNS policy based on a cluster wide config.

fix: support overriding k8s build pod dns config

---

config/pod.yaml.hbs
index.js

Support android emulator headless user tests
To support android emulator headless user tests, need to mount /dev/kvm host device as read-only. This PR will allow, host devices or host paths to be added as volume mounts to screwdriver pods.

fix: add host devices volume mounts

---

index.js
test/index.test.js

In Kata setup, build hangs indefinitely for any errors in build init step.
Update build status and status message for any errors in build init step.

fix: init step errors not propagated back to API

---

index.js
test/index.test.js

Reverts screwdriver-cd/executor-k8s#136
this works in opensource without any changes; will do some more checks why its not working internally and re-raise this PR if needed.

Revert "fix: init step errors not propagated back to API"

---

index.js
test/index.test.js

In Kata setup, build hangs indefinitely in init step for listed container waiting reasons 1. CrashLoopBackOff, 2. CreateContainerConfigError, 3. InvalidImageName, 4. CreateContainerError
Include additional container waiting reasons check 1. CrashLoopBackOff, 2. CreateContainerConfigError, 3. InvalidImageName, 4. CreateContainerError as part of pending retry strategy evaluation.

fix: init container stuck doesnt propagate error

---

index.js
test/index.test.js

In Kata setup, build hangs indefinitely in init step for "StartError" container waiting reason
Include "StartError" container waiting reasons as part of pending retry strategy evaluation.
PR https://github.com/screwdriver-cd/executor-k8s/pull/138

fix: add container waiting reason - StartError

---

index.js
test/index.test.js

When pod is scheduled with invalid image or container without sudo permission it should fail consistently and update build status and message appropriately, but it works intermittently. 
This could be due to delay in k8s updating pod status to failed. Add pod failed status check along-with container state waiting reason check.
https://github.com/screwdriver-cd/executor-k8s/pull/138
https://github.com/screwdriver-cd/executor-k8s/pull/139

fix: capture error when scheduling k8s pod

---

config/pod.yaml.hbs
index.js
test/index.test.js

Currently if a build is aborted the teardown steps don't run and hence generated artifacts are not available in this case, so we need to increase the grace period before pod termination to run the artifact saving steps
This PR adds provision to increase pod timeout by using annotations
https://github.com/screwdriver-cd/screwdriver/issues/1125

feat: add temination grace period to config

---

config/pod.yaml.hbs

Currently if a build is aborted the teardown steps don't run and hence generated artifacts are not available in this case, so we need to increase the grace period before pod termination to run the artifact saving steps
This PR adds pod timeout configuration to env var
https://github.com/screwdriver-cd/screwdriver/issues/1125

feat(1125): add terminationgraceperiod env var

---

README.md
config/pod.yaml.hbs
index.js
test/index.test.js

Cluster admins might want to configure custom pod labels.
This PR moves labels logic to the index.
Also adds config:
- to allow for custom pod labels (and will set default pod labels and custom ones accordingly)
- to set imagePullPolicy
- to configure imagePullSecrets name
Related to https://github.com/screwdriver-cd/screwdriver/issues/2265

feat(2265): Allow custom pod labels [2]

---

config/pod.yaml.hbs
index.js

SD needs to support docker layer cache natively for builds
This PR adds configurable dlc flag and path to executor

feat: add dlc flag and path to pod yaml

---

config/pod.yaml.hbs
index.js

DLC with mounting cache drive is slow with docker builds as it read writes from network drive so we cannot use this approach
This PR reverts changes for dlc mount

feat: Revert dlc changes

---

config/pod.yaml.hbs

We need to expose pod labels metadata to the container to display information
This PR uses K8s downwardAPI to mount the labels and annotations to the container as volume

feat: Add downwardAPI labels, annotations to pod

---

README.md
index.js
package.json
test/index.test.js

Pending builds with status like PodInitializing, ImagePullBackOff, etc need to be addressed separately without affecting the processing time of builds
This PR adds implementation of *verify* method to the executor to check for pod health
https://github.com/screwdriver-cd/screwdriver/issues/2491
https://github.com/screwdriver-cd/executor-k8s/pull/160
https://github.com/screwdriver-cd/executor-k8s/pull/161

feat: add verify method in executor to check pod status

---

config/pod.yaml.hbs

The dind image for build pod seems to be outdated.
update image tag to `20.10-dind`
- [Docker - Official Image | Docker Hub](https://hub.docker.com/_/docker)

feat: update dind image to 20.10

---

package.json

Request package is deprecated.
This PR removes the unused request package from the package.json.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1961

fix(1961): Remove request package

---

index.js
test/index.test.js

Verify function has additional retry logic and breaker fn which is not needed as we have the retry queue
verify function is called for messages in the retry-queue which already has a retry mechanism built into it, so we don't need this extra call that overwhelms the k8s api.

feat: remove extra retry logic from getpods fn

---

config/pod.yaml.hbs
index.js
package.json
test/index.test.js

Habitat installation needs to be optional for the launcher
This PR adds the flag `SD_HAB_ENABLED` to executors
https://github.com/screwdriver-cd/launcher/pull/429

feat(#1658): Make habitat installation configurable

---

config/pod.yaml.hbs

Allow the value set as resource limit in the build pod to be referenced as an environment variable at build time.
Add two environment variables to the build pod template.
- CONTAINER_CPU_LIMIT
- CONTAINER_MEMORY_LIMIT
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-container-fields-as-values-for-environment-variables

feat: Add resource limit values to environment variable [1]

---

index.js

When calling API for updateBuild, it should not retry if a response has 4XX status code.
It is taking longer to fail because of this retry.
Add retry option not to retry when a response has 4XX status code.

fix: Do not retry when statusCode 4XX

---

index.js
test/index.test.js

k8s hostname will be set from launcher by https://github.com/screwdriver-cd/launcher/pull/457 .
So we does not need to set hostname in executor-k8s.
Drop k8s hostname from build stats data when `executor.start` call.
https://github.com/screwdriver-cd/screwdriver/issues/2882

[2] fix(2882): drop k8s hostname from build stats data

---

config/pod.yaml.hbs
index.js
test/index.test.js

Pods might need more information.
This PR adds pipelineName, jobName, prNum, and template info to pod labels.
Blocked by https://github.com/screwdriver-cd/models/pull/592

fix: Add pipelineName, jobName, prNum, and template info to pod labels [2]

---

index.js
test/index.test.js

add cpu, memory, disk to pod labels
better tracking of builds in the context of k8s labels

fix: add cpu,memory,disk to pod labels

---

index.js

refer to https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

fix: pod label value is <= 63 in length

---

config/pod.yaml.hbs

If multiple builds which are getting scheduled in a node are trying to perform launcher upgrade, them mv can hang.
```
/opt/screwdriver/sdlauncher/v6.0.174 $ ls -al tmp.*
tmp.bJNieJ/ tmp.IdlIfa/ tmp.nhNfCN/
/opt/screwdriver/sdlauncher/v6.0.174/tmp.bJNieJ $ mv bin/ ../
mv: overwrite ‘../bin’? ^C
```

fix: for mv -f during launcher setup

---

index.js
test/index.test.js

Reverts screwdriver-cd/executor-k8s#186
If the launcher fails during the initialization container setup, [the node information for the build execution](https://github.com/sonic-screwdriver-cd/launcher/blob/5f9a44855bfc31b1bb4b947e408ca318a6f8e2c9/screwdriver/screwdriver.go#L446-L451) will not be updated. Rolling back this commit should enable the executor to update the node that the build is scheduled to run on, while still allowing the launcher to update the information afterward. If the hostname remains unchanged, the action should be idempotent regardless.
https://github.com/screwdriver-cd/screwdriver/issues/3089
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

fix(3089): restore k8s hostname into build stats data

---

index.js

In the [previous PR](https://github.com/screwdriver-cd/executor-k8s/pull/204), a lint error was found in the unit tests.
https://cd.screwdriver.cd/pipelines/28/builds/976493/steps/test
Fix lint Error
```bash
> screwdriver-executor-k8s@17.0.0 pretest
> eslint .
/Users/tminegis/work/src/github.com/sonic-screwdriver-cd/executor-k8s/index.js
294:16  warning  Constructor has too many statements (57). Maximum allowed is 50               max-statements
294:16  warning  Constructor has a complexity of 23. Maximum allowed is 20                     complexity
510:5   warning  Method 'createPodConfig' has too many lines (188). Maximum allowed is 150     max-lines-per-function
510:20  warning  Method 'createPodConfig' has too many statements (66). Maximum allowed is 50  max-statements
510:20  warning …
```

feat(3359): Fix lint
