index.js, test/index.test.js
Server is failing right now because filename `./config/job.yaml.tim` does not exist
=> Read from full path

index.js
need the ./ in front or else it would think /config is the directory
=> Make sure /config is not the root directory

index.js, test/index.test.js
Extra 's' in the url. Add more logging
=> Call the correct API

index.js, test/index.test.js
get request for logs needs authorization too
=> Pass in options for get logs request

config/job.yaml.tim
=> Upgrading to latest container

index.js, package.json, test/index.test.js
Also fixing tests to match hexadecimal requirements.
=> Allow passing of Job Name to build

config/job.yaml.tim
We'll need to figure out a CD solution for this :)
=> Using 0.2.2 container (fixes PR merging)

config/job.yaml.tim
Since we're going to be building ALL proposed PRs, let's not put secrets in the build yet.
=> Removing Secrets

README.md
Resolves https://github.com/screwdriver-cd/executor-k8s/issues/31
=> Add documentation for stop method

README.md, config/job.yaml.tim, index.js, package.json, test/index.test.js
- Mounts the /var/run/sd/emitter as a socket
- Adds the logservice container
=> Add logservice container and mount socket

README.md, index.js, package.json, test/index.test.js
Per https://github.com/screwdriver-cd/screwdriver/issues/135
Blocked on https://github.com/screwdriver-cd/executor-base/pull/16
=> Removing streaming (and updating circuit-fuses)

config/job.yaml.tim, index.js, package.json, test/index.test.js
New container: https://hub.docker.com/r/screwdrivercd/launcher
=> Switching to Launcher container and alternative service accounts

README.md, index.js, package.json, test/index.test.js
This now uses promises directly instead of callbacks.
Depends on https://github.com/screwdriver-cd/executor-base/pull/17
=> [prom-3] Switching to Promises

config/job.yaml.tim
- Logservice has 200Mi
- Added some more labels to identify these as Screwdriver containers
=> Configured jobs to have 2 gigs of ram

README.md, config/job.yaml.tim, index.js, package.json, test/index.test.js
This should not be merged until the new log service is available.
=> Supporting the new Log Service (and making more sane defaults)

index.js, package.json, test/index.test.js
Treat circuit-fuses as run-time dependency in tests
=> Use the circuit-fuses promise interface

config/job.yaml.tim
=> Fixing lint errors in the YAML

index.js, test/index.test.js
Relates to/Blocked by https://github.com/screwdriver-cd/screwdriver/pull/351
=> Pass in jobsNamespace

CHANGELOG.md, package.json, test/.eslintrc.yaml, test/index.test.js
This shouldn't create a new package and really shouldn't affect anything
=> chore: Catching up to new jenkins-mocha version

README.md, config/pod.yaml.tim, index.js, test/index.test.js
Related: screwdriver-cd/screwdriver#399
=> feat(399): allow prefix configuration

config/pod.yaml.tim
Create `/sd` directory in pod level
@jer
=> fix: create /sd in pod yaml

index.js, test/index.test.js
Add an ability to configure preferred node affinity like https://github.com/screwdriver-cd/screwdriver/issues/827.
This PR adds `setPreferredNodeSelector` and updates `setNodeSelector` to use `requiredDuringSchedulingIgnoredDuringExecution` and `preferredDuringSchedulingIgnoredDuringExecution` at the same time.
Some tests are not working so this PR also fixes some test by using `assert.deepEqual` and deep copy.
- Related: 
- https://github.com/screwdriver-cd/screwdriver/issues/972
- https://github.com/screwdriver-cd/executor-k8s/pull/76
- [Node affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature)
- [about weight](https://github.com/kubernetes/contrib/blob/fe159a635a0c4a5f4a3960cbef7f885091590dea/rescheduler/vendor/k8s.io/kubernetes/plugin …
=> feat(972): use preferred node affinity config

README.md, index.js, package.json, test/index.test.js
When a lot of pods of LOW resources are launched for build at once, the cluster resource drys up. That happens at our cluster actually, so it is PR to avoid such depletion.
Add MICRO pod resource.
=> feat: Micro resource

index.js, package.json
parse annotations and use standardized annotations
=> fix: parse annotations

README.md, index.js, package.json, test/index.test.js
- add turbo config for cpu and ram
- update circuit-fuses pkg
=> fix: add turbo config for cpu and ram

README.md, config/pod.yaml.tim, index.js, test/index.test.js
make launcher image configurable so that ppl can use launcher img from their own docker registry
=> fix: make launcher image configurable

package-lock.json, package.json
update dependencies to resolve security alerts
=> fix: update dependencies to resolve security alerts

config/pod.yaml.hbs, index.js, package.json
Disk-based cache strategy implementation missing in executor-k8s.
Add disk-based cache strategy implementation.
[Build cache - disk storage strategy](https://github.com/screwdriver-cd/screwdriver/issues/1830)
=> feat(818): Evaluate Kata Containers over HyperD

config/pod.yaml.hbs
=> fix: k8s string check

config/pod.yaml.hbs
missing NODE_ID metrics
add NODE_ID to metrics
=> feat(818): add nodename to metrics

index.js, test/index.test.js
it will be useful to have extra logic to apply as container lifecycle
added `lifecycle` specs to the build container and fixed the tests
=> feat: add lifecycle hooks to container

config/pod.yaml.hbs
Update cpu config and add runtime class environment variable.
=> fix: cpu config and add runtime env

config/pod.yaml.hbs
Fix this Issue.
https://github.com/screwdriver-cd/screwdriver/issues/2116
Change `PUSHGATEWAY_URL` to `SD_PUSHGATEWAY_URL`.
https://github.com/screwdriver-cd/screwdriver/issues/2116
[1] https://github.com/screwdriver-cd/executor-k8s/pull/129 <- this PR
[2] https://github.com/screwdriver-cd/executor-k8s-vm/pull/74
[3] https://github.com/screwdriver-cd/launcher/pull/361
=> fix(2116): [1] Change PUSHGATEWAY_URL to SD_PUSHGATEWAY_URL

config/pod.yaml.hbs, index.js
add cache max go threads config
https://github.com/screwdriver-cd/store-cli/pull/61
=> fix: add cache max go threads config

config/pod.yaml.hbs, index.js
add volume mount type
https://github.com/screwdriver-cd/executor-k8s/pull/134 
=> fix: add volume mount type

README.md, config/pod.yaml.hbs, index.js, test/index.test.js
Reverts screwdriver-cd/executor-k8s#144
Unblock pipeline
=> fix: Revert "feat(2265): Allow custom pod labels [2]"

config/pod.yaml.hbs
fix error on env var value not being string
=> fix: env string in quotes

README.md, config/pod.yaml.hbs, index.js, test/index.test.js
Reverts screwdriver-cd/executor-k8s#146
=> fix: Revert Revert "feat(2265): Allow custom pod labels [2]"

config/pod.yaml.hbs, index.js
Support Docker layer cache feature for SD
This PR fixes the hostpath in pod yaml and adds defaults
=> feat: fix host path for dlc and add defaults

config/pod.yaml.hbs, index.js
SD dlc feature
This PR corrects the property name for dlc flag
=> feat: fix property name bug

config/pod.yaml.hbs
sd dlc feature
This PR fixes and indentation issue with pod.yaml
=> feat: fix yaml indentation

config/pod.yaml.hbs
SD DLC feature
This PR removes dlc mount from init container to main container 
=> feat: move dlc mount from init to container

config/pod.yaml.hbs
share volume between dind and build container
=> fix: share volume between dind and build container

index.js
Adding some logs and using ES6 features
This PR adds some log information, refactors some code and converts functions to async-await
=> feat: refactor some code and add logs for debug

config/pod.yaml.hbs, index.js
Add sshca secret to pod template
Add sshca secret to pod template
=> adding ssh secret to pod template

index.js
Retry format requires throwing error to correctly trigger.
This PR:
- throws error in retry strategy in `afterResponse` hook to correctly trigger retries
- adds retry for 200 status code
Related to https://github.com/screwdriver-cd/screwdriver/issues/1961
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.
=> fix(1961): Retry with new request package

config/pod.yaml.hbs
secret env was placed in wrong section
move it to build container section
=> fix: move secret env

config/pod.yaml.hbs
=> fix: do not expand if /hab is empty

config/pod.yaml.hbs
same in https://github.com/screwdriver-cd/executor-k8s/pull/184
=> fix: do the same as in #184

index.js, test/index.test.js
sanitize k8s labels correctly or else it won't work at all
=> fix: sanitize k8s labels correctly

index.js
need to check for non alphanumerical at the start and at the end
=> fix: label sanitation

config/pod.yaml.hbs
Adding -n option to skip overwrite of files during move
=> fix: Update pod.yaml.hbs to update mv command
